# Site settings
title: Hog's Blog
email: 614166392@qq.com
description: > # this means to ignore newlines until "baseurl:"
  This is Hogzhu's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Hogzhu
github_username:  Hogzhu

# Build settings
markdown: kramdown
